### ISSUE TITLE
不能install

### ISSUE THREAD

**Issue by ghost** [SkyLothar/flask-wechat#1]
```
$ pip install https://github.com/skylothar/flask-wechat
Collecting https://github.com/skylothar/flask-wechat
  Downloading https://github.com/skylothar/flask-wechat
     | 71kB 415kB/s
  Cannot unpack file /private/var/folders/sy/hmknm52s79920dgr_dcs_fj00000gn/T/pip-08PX2P-unpack/flask-wechat (downloaded from /var/folders/sy/hmknm52s79920dgr_dcs_fj00000gn/T/pip-yyLNnD-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /var/folders/sy/hmknm52s79920dgr_dcs_fj00000gn/T/pip-yyLNnD-build
```

What is this error?

**Comment by SkyLothar** [comment]
`pip install git+https://github.com/skylothar/flask-wechat`
就好了需要告诉pip是git

你想做公众号吗？

**Comment by ghost** [comment]
对，正在测试wechat 的api

`pip install git+https://github.com/skylothar/flask-wechat` 在我的local电脑就没问题，

但是在production server (pythonanywhere) 就看到这些问题

```
(venv) 18:35 ~/Paw (local_flask_wechat)$ pip install git+https://github.com/skylothar/flask-wechat                                                                                                                                                                                      
Collecting git+https://github.com/skylothar/flask-wechat
  Cloning https://github.com/skylothar/flask-wechat to /tmp/pip-eWLSKU-build
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.10.0 in /home/vicngtor/.virtualenvs/venv/lib/python2.7/site-packages (from flask-wechat==0.0.1)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.0.0 in /home/vicngtor/.virtualenvs/venv/lib/python2.7/site-packages (from flask-wechat==0.0.1)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.8.0 in /home/vicngtor/.virtualenvs/venv/lib/python2.7/site-packages (from flask-wechat==0.0.1)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /home/vicngtor/.virtualenvs/venv/lib/python2.7/site-packages (from Flask>=0.10.0->flask-wechat==0.0.1)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /home/vicngtor/.virtualenvs/venv/lib/python2.7/site-packages (from Flask>=0.10.0->flask-wechat==0.0.1)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /home/vicngtor/.virtualenvs/venv/lib/python2.7/site-packages (from Flask>=0.10.0->flask-wechat==0.0.1)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /home/vicngtor/.virtualenvs/venv/lib/python2.7/site-packages (from Jinja2>=2.4->Flask>=0.10.0->flask-wechat==0.0.1)
Installing collected packages: flask-wechat
  Running setup.py install for flask-wechat ... done
Successfully installed flask-wechat-0.0.1
(venv) 18:36 ~/Paw (local_flask_wechat)$ stdbuf -o0 tail -f /var/log/vicngtor.pythonanywhere.com.error.log                                                                                                                                                                              
  File "/bin/user_wsgi_wrapper.py", line 170, in import_error_application
    raise e
ImportError: No module named flask.ext.wechat.WeChat
2016-05-20 18:35:21,617 :Error running WSGI application
Traceback (most recent call last):
  File "/bin/user_wsgi_wrapper.py", line 154, in __call__
    app_iterator = self.app(environ, start_response)
  File "/bin/user_wsgi_wrapper.py", line 170, in import_error_application
    raise e
ImportError: No module named flask.ext.wechat.WeChat
2016-05-20 18:36:31,781 :Error running WSGI application
Traceback (most recent call last):
  File "/bin/user_wsgi_wrapper.py", line 154, in __call__
    app_iterator = self.app(environ, start_response)
  File "/bin/user_wsgi_wrapper.py", line 170, in import_error_application
    raise e
ImportError: No module named flask.ext.wechat.WeChat
```

您可以update pip 的版本吗？

**Comment by SkyLothar** [comment]
...我看了一下...
pypi上的flask-wechat不是我写的
是 https://github.com/Xavier-Lam/flask-wechat/
我可能会改个名字

**Comment by SkyLothar** [comment]
pip install flask-wechat-kit
